version: '3.8'


services:
  db:
    image: postgres:16.0
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  api:
    container_name: api
    build: ../../backend
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../../backend/app:/backend/app
    ports:
      - "8000:8000"
    command: ["sh", "entrypoint.sh"]
